service: xconf-specs

provider:
  name: google
  runtime: nodejs
  project: x-conf
  credentials: ~/.gcloud/XConf-keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  graphql:
    handler: graphql
    events:
      - http: path
